---
- name: Backup Server
  hosts: backup_servers
  become: yes
  vars_files:
  - all_vars.yml
  roles:
    - backup_server

- name:  Client
  hosts: clients
  become: yes
  vars_files:
  - all_vars.yml
  roles:
    - client
